import './globals.css'
import { Inter, Encode_Sans } from 'next/font/google'
import { AuthContext, AuthContextProvider } from '@/context/AuthContext'
import NavBar from '@/components/NavBar'
import { useContext } from 'react'
const encode = Encode_Sans({ subsets: ['latin'] })
export const metadata = {
  title: 'Quoted',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={encode.className}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
        <NavBar/>
      </body>
    </html>
  )
}
